# Generated by Django 5.1.3 on 2024-12-04 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Rasmi')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Mashina qo'shilgan vaqti")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.categorymodel', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Mashina',
                'verbose_name_plural': 'Mashinalar',
                'db_table': 'Cars',
                'managed': True,
            },
        ),
    ]
