# Generated by Django 5.1.3 on 2024-12-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('comfort', models.CharField(choices=[('cheap', 'Ekanom'), ('standart', 'Standart'), ('lux', 'Lyuks')], max_length=10)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Jalb qilish',
                'verbose_name_plural': 'Jalb qilishlar',
                'db_table': 'Booking',
                'managed': True,
            },
        ),
    ]
